/**
 * Combined Algorithm-Based Questions for ECCCO Platform
 * 
 * This file contains all questions generated from emergency medicine algorithms
 * including ACLS, ATLS, Sepsis protocols, and other major clinical guidelines.
 * 
 * Auto-generated by running: npx tsx scripts/generate-algorithm-questions.ts
 */

import { Question } from './types';

// Import all algorithm question files
import { aclscardiacarrestQuestions } from './acls-cardiac-arrest-questions';
import { sepsishour1bundleQuestions } from './sepsis-hour-1-bundle-questions';
import { atlsprimarysurveyQuestions } from './atls-primary-survey-questions';
import { strokeacutemanagementQuestions } from './stroke-acute-management-questions';
import { pediatriccardiacarrestQuestions } from './pediatric-cardiac-arrest-questions';
import { anaphylaxismanagementQuestions } from './anaphylaxis-management-questions';
import { toxicologyoverdoseQuestions } from './toxicology-overdose-questions';
import { massivetransfusionQuestions } from './massive-transfusion-questions';
import { diabeticketoacidosisQuestions } from './diabetic-ketoacidosis-questions';

export const algorithmQuestions: Question[] = [
  ...aclscardiacarrestQuestions,
  ...sepsishour1bundleQuestions,
  ...atlsprimarysurveyQuestions,
  ...strokeacutemanagementQuestions,
  ...pediatriccardiacarrestQuestions,
  ...anaphylaxismanagementQuestions,
  ...toxicologyoverdoseQuestions,
  ...massivetransfusionQuestions,
  ...diabeticketoacidosisQuestions
];

export default algorithmQuestions;

// Generation metadata
export const GENERATION_METADATA = {
  totalQuestions: algorithmQuestions.length,
  totalAlgorithms: 9,
  generatedOn: new Date().toISOString(),
  algorithms: [
    'acls-cardiac-arrest',
    'sepsis-hour-1-bundle', 
    'atls-primary-survey',
    'stroke-acute-management',
    'pediatric-cardiac-arrest',
    'anaphylaxis-management',
    'toxicology-overdose',
    'massive-transfusion',
    'diabetic-ketoacidosis'
  ],
  categories: [
    'cardiac',
    'sepsis',
    'trauma', 
    'neurological',
    'pediatric',
    'respiratory',
    'toxicology'
  ],
  coverage: {
    'ACLS Cardiac Arrest': aclscardiacarrestQuestions.length,
    'Sepsis Hour-1 Bundle': sepsishour1bundleQuestions.length,
    'ATLS Primary Survey': atlsprimarysurveyQuestions.length,
    'Stroke Management': strokeacutemanagementQuestions.length,
    'Pediatric ACLS': pediatriccardiacarrestQuestions.length,
    'Anaphylaxis': anaphylaxismanagementQuestions.length,
    'Toxicology': toxicologyoverdoseQuestions.length,
    'Massive Transfusion': massivetransfusionQuestions.length,
    'DKA Management': diabeticketoacidosisQuestions.length
  }
};